db:
  db_file: local.db

default_dirs:
  db: ./ohmyscrapper_db
  input: ./ohmyscrapper_input
  output: ./ohmyscrapper_output
  prompts: ./ohmyscrapper_prompts
  templates: ./ohmyscrapper_templates
  cache: ./ohmyscrapper_cache

default_files:
  url_types: url_types.yaml
  url_sniffing: url_sniffing.yaml

ai:
  default_prompt_file: prompt.md

sniffing:
  timeout: 10
  use-browser: false
  browser-headless: false
  browser-container-options: false
  browser-arguments: []
  browser-pool-size: 1
  browser-waiting-time: 5
  round-sleeping: 10
  request-delay-min: 1
  request-delay-max: 3
  retry-count: 0
  retry-backoff: 0
  proxies: []
